AWSTemplateFormatVersion: '2010-09-09'
Resources:
  CustomerTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: Customer
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
      KeySchema:
        - AttributeName: id
          KeyType: HASH
      BillingMode: PAY_PER_REQUEST
      GlobalSecondaryIndexes: []
      SSESpecification:
        SSEEnabled: true

  GoforTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: Gofor
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
      KeySchema:
        - AttributeName: id
          KeyType: HASH
      BillingMode: PAY_PER_REQUEST
      SSESpecification:
        SSEEnabled: true

  OrderTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: Order
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
        - AttributeName: CustomerId
          AttributeType: S
        - AttributeName: GoforId
          AttributeType: S
      KeySchema:
        - AttributeName: id
          KeyType: HASH
      BillingMode: PAY_PER_REQUEST
      SSESpecification:
        SSEEnabled: true

  ReviewsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: Reviews
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
      KeySchema:
        - AttributeName: id
          KeyType: HASH
      BillingMode: PAY_PER_REQUEST
      SSESpecification:
        SSEEnabled: true

  RatingTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: Rating
      AttributeDefinitions:
        - AttributeName: GoforId
          AttributeType: S
      KeySchema:
        - AttributeName: GoforId
          KeyType: HASH
      BillingMode: PAY_PER_REQUEST
      SSESpecification:
        SSEEnabled: true
